apiVersion: v1
kind: Pod
metadata:
  name: retail-pod
  namespace: likhitha-ns
  labels:
    app: retail
  spec:
   containers:
    - name: retail-container
      image: likhithabhogyam/retail-inventory-app
      ports:
        - containerPort: 3000